### PR TITLE
Less pkg, mo mojo

### PR DESCRIPTION
**Pull request by nternetinspired**
Hey Andrew,

I noticed that many of the postcss packages included replicate functionality already included in http://cssnext.io/ and it's successor https://preset-env.cssdb.org/.

This PR removes Autoprefixer, post-css-extend, postcss-hexrgba, postcss-nested, postcss-nested-ancestors and postcss-simple-vars; the functionality they provide is all provided I believe by the most awesome postcss-preset-env: https://preset-env.cssdb.org/features

Options, such as those for Autoprefixer can be passed directly to postcss-preset-env instead. My postcss config, for example, contains: 

```
module.exports = {
  plugins: [
    require("postcss-import")({
      plugins: [
        require("stylelint"),
      ]
    }),
    require('postcss-preset-env')({
      autoprefixer: { grid: true }
    }),
    require('postcss-normalize'),
    require('postcss-easing-gradients'),
    require('tailwindcss')('./tailwind.config.js')
  ]
};
```

### CODE REVIEW

**Comment by khalwat** [comment]
Great, thank you @nternetinspired -- I will test the changes and see if there are any implications.

**Comment by khalwat** [comment]
Seems to work great, thank you!

**Comment by khalwat** [comment]
@nternetinspired in case you have any input on this... I'm oddly not seeing things being auto-prefixed using this setup? I've read the docs, and it doesn't seem like we're doing anything wrong, though.

https://github.com/csstools/postcss-preset-env#autoprefixer

https://github.com/browserslist/browserslist#queries

**Comment by khalwat** [comment]
Figured it out... it _was_ working... but not for anything that Tailwind generated, because it needs to be required _after_ it. I'll update the config.

**Comment by nternetinspired** [comment]
Good catch @khalwat, apologies for not correcting the ordering myself; I should have spotted that. My current setup is:

```
module.exports = {
    plugins: [
      require('postcss-import')({
        plugins: [
          require('stylelint'),
        ]
      }),
      require('postcss-normalize'),
      require('tailwindcss')('./tailwind.js'),
      require('postcss-preset-env')({
        autoprefixer: { grid: true },
        features: {
          'nesting-rules': true
        }
      })
    ]
};
```

**Comment by khalwat** [comment]
You'll hear all about it on the next episode of https://devmode.fm/ -- comes out on Monday January 7th! :)

I like your defaults, and will adopt them into the project repo too

**Comment by khalwat** [comment]
So I ended up with this:

https://github.com/nystudio107/annotated-webpack-4-config/commit/f669742a6fd7d19878b3ea42b95a485415040685

Note the use of `stylelint-config-recommended` and added `.stylelintrc.json` to use it, and override the warnings about Tailwind specific things.

**Comment by nternetinspired** [comment]
Nice one, I look forward to the podcast.

**Pull request merged**
